name: Build GS334 iOS IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Web
        run: npm run build

      - name: Install Capacitor
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/ios

      - name: Sync iOS
        run: npx cap sync ios

      - name: Install CocoaPods
        run: |
          cd ios/App
          pod install

      - name: Build iOS
        run: |
          cd ios/App
          xcodebuild \
          -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -sdk iphoneos \
          CODE_SIGNING_ALLOWED=NO \
          archive \
          -archivePath build/App.xcarchive

      - name: Export IPA
        run: |
          mkdir export

          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>signingStyle</key>
              <string>manual</string>
          </dict>
          </plist>
          EOF

          xcodebuild \
          -exportArchive \
          -archivePath ios/App/build/App.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath export

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: GS334-iOS
          path: export
